---
server: false

markdown: kramdown

pygments: true
permalink: pretty

host: http://rubini.us

exclude:
  - drafts
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Rakefile.compiled.rbc
  - .rvmrc
  - rubini.us.gems
---
